### PR TITLE
Updating Sagemaker Notebooks and small changes to the compute resources

### PR DESCRIPTION
**Pull request by tobias-gp**
Changes to metaflow-cfn-template.yml: 
1. Removed all SageMaker notebook dependencies 
2. Explicitely created the ECS instance role
3. Changed the compute environment to not hold any machines in standby for cost-reasons
4. Adding P-Instances to enable GPU compute
5. Autoformatter removed some trailing spaces :) 

New file metaflow-notebook-cfn-template.yml: 

1. Changed the permissions to also execute Metaflow tasks (not just use the client)
2. Lifecycle config changes: Write config file to $METAFLOW_HOME, shut down notebook after idle time, and automatically pull the Metaflow Tutorials to the Jupyter Notebook home in /home/ec2-user/SageMaker

### CODE REVIEW

**Comment by jsaedtler** [comment]
Looks good to me.

Do you have any kind of testing for your templates at netflix @savingoyal ?

**Comment by savingoyal** [comment]
@tobias-gp Would it be helpful to make SageMaker setup optional in the first template? That way, consumers will only have to worry about a single template. Other changes look good to me. 

@jsaedtler We have been relying on @queueburt's mad cfn skills for testing our templates so far :)

**Comment by tobias-gp** [comment]
Hi Savin,

Thanks for your feedback! Just to be clear: do you mean (1) a full merge of the two templates and making the setup optional or (2) retaining the two templates with Metaflow stack (+ notebook stack), and notebook  stack. This would of course induce some redundancy. 

The reason why we separated the two was because of the 1:N relationship of stacks to notebooks. I am fine with any solution, but on that case (1) seems more logical.

**Comment by tobias-gp** [comment]
Ping :)

**Comment by savingoyal** [comment]
Oops. Sorry, I thought I replied earlier, but clearly not. 
1. Yes, ideally it would be better to just have a single cloud formation template (with optional Sagemaker setup). We can have separate notebooks only template in a different folder in addition.
2. We can leave the `Default` for MinVCPUBatch to 8 and pin the `MinValue` to 0. The reason, why we chose not to set the default to 0 was because then it invariably leads to higher job start-up times leading to degraded user experience. By default, we can leave it to a non-zero value and our cost-conscious users can override it to 0 (which is currently not the case at the tip of the master.)

**Comment by savingoyal** [comment]
Also, we are making a few more changes to the permissions in #13 to support SFN.

**Comment by tobias-gp** [comment]
@savingoyal : Thanks for your feedback. 

1. I have just removed the NB template, which we could do in a separate PR
2. I have also integrated the API key handling into the lifecycle config
3. `MinVCPUBatch` is now set to 8 with `MinValue` set to 0. 
4. I have also added a section in Readme.md to discuss potential cost savings

**Comment by savingoyal** [comment]
@queueburt Can you assist on this PR?

**Comment by tobias-gp** [comment]
Ping? :)

**Comment by queueburt** [comment]
> Ping? :)

Hey Tobias, I have a PR I just finished that includes necessary bits for Step Functions [here](https://github.com/Netflix/metaflow-tools/pull/13) (#13), but I also incorporated some of your feedback along the way regarding non-singular ECS Task roles and optionality of Sagemaker Notebooks.  I'll glance over this PR early next week and try to work out what gaps we need to reconcile between the two, but could I trouble you to do the same for mine?  I'd love to combine these both together into one clean result.

**Comment by tobias-gp** [comment]
@queueburt : Sorry for the slow reply. I agree that bringing in the structural changes first makes sense!

**Pull request closed without merging**
